# Generated by Django 4.1.7 on 2023-02-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('student_class', models.IntegerField(choices=[(1, 'B.C.A. Ist'), (2, 'B.C.A. 2nd'), (3, 'B.C.A. 3rd')])),
                ('student_email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('question', models.TextField()),
            ],
        ),
    ]
